### ISSUE TITLE
Missing text for radio buttons

### ISSUE THREAD

**Issue by bernardyip** [voythas/shine-unofficial#1]
![image](https://user-images.githubusercontent.com/1573143/31314484-2f10047a-ac34-11e7-9d04-242e8f8e2187.png)

Missing text in the settings
This is in the develop branch

**Comment by voythas** [comment]
Yeah, this whole view is WIP. Those radio buttons will replace theme dropdown, sorry about that, I created this repo in middle of working on it. Thank you for reporting tho.

**Comment by voythas** [comment]
Fixed in new version.
