### ISSUE TITLE
Saved icon missing on state

### ISSUE THREAD

**Issue by skeemer** [voythas/shine-unofficial#11]
I've created a patch that will show when an item as been saved.
`
diff --git a/shine-grid.css b/shine-grid.css
index 7f3ef01..d613f25 100644
--- a/shine-grid.css
+++ b/shine-grid.css
@@ -231,6 +231,10 @@ html.SHINE.shine-grid body > .content #siteTable .thing ul.flat-list li.save-but
     background-size: 18px;
 }
 
+html.SHINE.shine-grid body > .content #siteTable .thing.saved ul.flat-list li.save-button a{
+    background-image: url(data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48c3ZnIHZlcnNpb249IjEuMSIgaWQ9IkxheWVyXzEiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgeG1sbnM6eGxpbms9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkveGxpbmsiIHg9IjBweCIgeT0iMHB4IiB2aWV3Qm94PSItMzEzIDQwMy43IDIwIDE5IiBzdHlsZT0iZW5hYmxlLWJhY2tncm91bmQ6bmV3IC0zMTMgNDAzLjcgMjAgMTk7IiB4bWw6c3BhY2U9InByZXNlcnZlIj48cGF0aCBkPSJNLTMwMyw0MTguOWw2LjIsMy43bC0xLjYtN2w1LjUtNC43bC03LjItMC42bC0yLjgtNi42bC0yLjgsNi42bC03LjIsMC42bDUuNSw0LjdsLTEuNiw3TC0zMDMsNDE4Ljl6IiBmaWxsPSJyZ2IoMjU1LDIxNSwwKSIvPjwvc3ZnPg==);
+}
+
 html.SHINE.shine-grid body > .content #siteTable .thing ul.flat-list .hide-button a{
 	width: 15px;
     text-indent: 100%;
`

**Comment by dotvhs** [comment]
Thanks, I will look into it.

**Comment by skeemer** [comment]
Here's the actual patch file.
[star.patch.txt](https://github.com/voythas/shine-unofficial/files/1590764/star.patch.txt)

**Comment by dotvhs** [comment]
Soon I will be releasing 1.7.0 which this will be included. I know it's been a while, thanks again for your contribution.
