### ISSUE TITLE
Unstyled action buttons on self posts

### ISSUE THREAD

**Issue by sepehr** [voythas/shine-unofficial#12]
![image](https://user-images.githubusercontent.com/23576/34340992-1992cc84-e9a3-11e7-88af-72cbccdfe4ef.png)

**Comment by dotvhs** [comment]
Thanks for reporting, I noticed it before. It should be fixed in future version. I'm slowly getting back to Shine.

**Comment by dotvhs** [comment]
Sorry for the delay, i found the fix for this it should be live in a week or less.
