### ISSUE TITLE
Don't Act on Modmail

### ISSUE THREAD

**Issue by Foggalong** [voythas/shine-unofficial#15]
Shine appears to be trying to change the styling of the [modmail page](https://mod.reddit.com/mail/all), which is a fools errand since it uses completely different styling to the rest of Reddit. Easy fix would be be to exclude pages matching `mod.reddit.com/*` 
 
![2018-01-21-234421_1920x1080_scrot](https://user-images.githubusercontent.com/5920259/35200373-11b72a38-ff05-11e7-956b-b5c99cf65ef5.png)

**Comment by dotvhs** [comment]
Yeah, it seems to be the part of the new Reddit layout. I'll make my own subreddit and see what can be done about it. It might also tell me something about the new layout as well.

**Comment by dotvhs** [comment]
This should be fixed in upcoming 1.7.0 version.
