### ISSUE TITLE
Mod Settings

### ISSUE THREAD

**Issue by Foggalong** [voythas/shine-unofficial#16]
Further to what was mentioned in #15 about the modmail, a lot of the moderator functionality just straight up doesn't work if Shine is enabled. Things like changing the flair of a post and reviewing the modqueue are either much harder to do or just aren't possible. It means every time I need to do mod work I have to disable Shine which gets tiresome :confused:

**Comment by dotvhs** [comment]
Oh, I think I will have to create my own subreddit to see what's wrong with it. Thanks for reporting.

**Comment by dotvhs** [comment]
This should be (hopefully) fixed in 1.7.0. Will need further testing, feel free to send another issue after 1.7.0 release if it won't work.
