### ISSUE TITLE
image not showing

### ISSUE THREAD

**Issue by ghost** [voythas/shine-unofficial#23]
hello, black space instead of displaying the image and once you click on that post it generate hundred of errors  : 

![shine](https://user-images.githubusercontent.com/33638320/37949017-05711354-3193-11e8-994c-1c66bc4e83e9.png)

![gg](https://user-images.githubusercontent.com/33638320/37949407-cc816ef2-3194-11e8-97a4-0bd17640ed43.png)

shine 
`<div class="large-image" style="background-image:url(undefined);"></div>`

full page:

`<div class="media-preview-content"><a href="https://i.redd.it/8vqoz72k97o01.gif" class="may-blank"><video class="preview" preload="auto" autoplay="autoplay" muted="muted" loop="loop" webkit-playsinline="" style="width: 560px; height: 560px;"><source src="https://g.redditmedia.com/Q0eR1enY4QINcggsJJS5K2tJqfFapqOkBfr3z32H3Sw.gif?w=560&amp;fm=mp4&amp;mp4-fragmented=false&amp;s=cf950131be383f5a1c6a7415f84a3835" type="video/mp4"></video></a></div>`

**Comment by dotvhs** [comment]
Could you link me that thread?

**Comment by dotvhs** [comment]
This should be fixed in 1.7.0.
