### ISSUE TITLE
Double lock icons showing up before a user Authenticates

### ISSUE THREAD

**Issue by damengilland** [voythas/shine-unofficial#25]
## Issue

Currently the user sees two lock icons before they log in.  Both seem to open the same panel.

<img width="785" alt="screen shot 2018-04-02 at 5 51 57 pm" src="https://user-images.githubusercontent.com/1106778/38188269-90e47ce0-369e-11e8-97b6-14cf4a47a821.png">

## Expectation

I should only see one lock "Log In" button.

**Comment by dotvhs** [comment]
Interesting, I will look into that in the future.

**Comment by dotvhs** [comment]
This will be fixed in upcoming 1.7.0 version.
