### ISSUE TITLE
/subscriptions/ shows stack of unlabeled unscribe buttons when hovering over the shine button

### ISSUE THREAD

**Issue by RickyGrassmuck** [voythas/shine-unofficial#26]
When viewing /subreddits/, the shine menu button shows a stack of the unsubscribe buttons. These are all unlabeled so they are not very useful and if you are subscribed to a large number of subreddits the menu becomes cluttered.

![shine](https://user-images.githubusercontent.com/17223437/38262543-1da45756-3733-11e8-9382-770f1c982cd6.PNG)

I think that blacklisting the /subreddits/ URI so the icons don't get displayed in there would likely be the best option since that feature should probably be limited to actual subreddits.

**Comment by dotvhs** [comment]
Oh wow, yeah, I will look into that.

**Comment by dotvhs** [comment]
I already fixed that in upcoming version 1.7.0
