### ISSUE TITLE
Add support for new Reddit Redesign

### ISSUE THREAD

**Issue by zachthedev** [voythas/shine-unofficial#28]
Will the new redesign ever be supported? It was a huge overhaul so I am not expecting anything, but it would be wonderful if you could make it happen, thanks!

**Comment by zachthedev** [comment]
@voythas

**Comment by dotvhs** [comment]
This would require almost full rewrite of the code.

My current  statement is: I am not going to do that. Things may change tho.

**Comment by zachthedev** [comment]
Thank you, if you ever get around to it, feel free to let me know, thanks!
