### ISSUE TITLE
Conflict and its markers left in base.js

### ISSUE THREAD

**Issue by RickyGrassmuck** [voythas/shine-unofficial#29]
Looks like there was a conflict left in the base.js file along with its conflict markers. Seems to have come from the last commit merging develop into master. The link below takes you straight to the line in question.

[base.js#L107](https://github.com/voythas/shine-unofficial/blob/6cb28be5525c69a1c31b383cae4b5c96b2ce5384/base.js#L107)

**Comment by dotvhs** [comment]
Thank you for pointing that out. I will fix it soon.

**Comment by dotvhs** [comment]
Closing this as it's already fixed on my end and will be released in 1.7.0.
