### ISSUE TITLE
Support for v.redd.it etc in Grid View

### ISSUE THREAD

**Issue by voythas** [voythas/shine-unofficial#3]
Currently I added support for new sources only for List View. I need to add the same for Grid View.

Note to self: look into moving support for sources into one single file instead.

**Comment by voythas** [comment]
v.redd.it and clips.twitch.tv are done, need to fix gfycat in grid and add support for few nsfw.

**Comment by kutsan** [comment]
I didn't want to create an issue for this. I know this is not even relevant for this issue but thanks for keeping the extension alive! Keep it up!

**Comment by selfdigest** [comment]
I just started using shine this week, but noticed I'm getting the complete opposite of this. v.redd.it works, but only in grid view. When in either of the list views, it just show the empty black area where the video should be.

I see no mention of this anywhere else, and disabled other extensions in chrome just to make sure, but still no go.

//Edit: Fixed below

**Comment by selfdigest** [comment]
Just want to update. After getting annoyed that it seems to be an isolated issue, I did some digging and got it fixed.

It's the "Media Previews" option in reddit settings. I had it set to "Don't auto-expand media previews on comments pages" originally, which results in just a black blank spot for v.reddit videos. Switching it to "Auto-expand media previews" has fixed it completely.

Feel stupid for not checking that already. lol

**Comment by dotvhs** [comment]
Ah, alright, that's important info anyway. Thanks for providing the way you fixed it.
