### ISSUE TITLE
Disabling styling for the new design

### ISSUE THREAD

**Issue by ashokduddukuri** [voythas/shine-unofficial#31]
I love shine for Reddit, thanks for maintaining it. I use it daily with old.reddit.com and everything looks fine. But when a link is opened form google search, Reddit defaults to the latest design and everything looks bad. Making it compatible is hard, can we at least disable the styling in the latest design. lemme know if this is okay. I'll send PR.

**Comment by dotvhs** [comment]
You can disable the new style in your profile settings, it will revert the Reddit to old theme. I will look into ways of implementing that though.

**Comment by dotvhs** [comment]
Okay, so in next version I added a modal box that shows info how to disable new design entirely. It should not stylize anything in new reddit.

**Comment by dotvhs** [comment]
Forgot to mention: the next version launches this month, I have no idea when exactly.
