### ISSUE TITLE
Clicking "edit" on a comment opens a blank new tab

### ISSUE THREAD

**Issue by jmcblane** [voythas/shine-unofficial#32]
When attempting to edit a comment from the listing page; clicking the edit link under the comment opens a new, blank tab.

**Comment by dotvhs** [comment]
Where exactly? I can't reproduce this bug.

**Comment by jmcblane** [comment]
On my "Front New" page (reddit.com/new). _[The bug happens on any listing page, when editing a comment from the expanded post on the listing page.]_ Attached is an animated screenshot of the bug in action.
I am running Arch Linux, using Firefox 62.

![shinebug](https://user-images.githubusercontent.com/25023928/45655481-7f712f00-baae-11e8-8284-f294c5aa2ffd.png)

**Comment by dotvhs** [comment]
Thanks for the vid, now I fully understand the issue and I just checked - it's happening for me as well. I will try to find the cause for this behavior.

**Comment by dotvhs** [comment]
Okay, I located the issue and fixed it, it will be added in upcoming 1.7.0.
