### ISSUE TITLE
Tile recycling

### ISSUE THREAD

**Issue by brezinajn** [voythas/shine-unofficial#5]
Hi,
after a time shine becomes slow and unresponsive. After short testing it seems it's memory issue (the more I scroll, the more memory tab takes). I presume this could be fixed by recycling tiles that are not on screen. By the way great job maintaining shine after the official fiasco :).

**Comment by voythas** [comment]
Thank you for the kind words. I will look into it, although I am not very skilled in JS, so it might be too much for me. I'll try tho.

Thanks for reporting this.

**Comment by voythas** [comment]
Nevermind, I think I did it. Try the latest develop version. Currently it's only customizable for list view, grid is currently hard-coded, I just have to go to sleep already and wanted to push it quick so you could test it out.

**Comment by brezinajn** [comment]
Much better :) Used memory still goes up, but at a **much** slower rate. It tells me there is still some leakage. Do you unload old data from api as well?

**Comment by voythas** [comment]
Shine is not API based, it's full AJAX and scrapping the webpage. 

Currently I'm just destroying old DOMs and that's all about it for now. I might look into it further, but as I mentioned, I'm more of a frontend guy rather than backend. I'll read about it tho.

**Comment by brezinajn** [comment]
My bad :(. You understood the question though :). Thanks for clarification.

**Comment by voythas** [comment]
No worries, btw thanks for requesting this, I'm pretty sure many people will find it very helpful.

There still might be a code that is duplicating some DOMs, current version is more of a concept, I'll definately work on it more and feedback is very welcome.

I'm leaving this issue open until I finish the code.

**Comment by brezinajn** [comment]
Works well in new release :)

**Comment by voythas** [comment]
Great :) I'm closing the issue then.
