### ISSUE TITLE
Settings modal not styled properly

### ISSUE THREAD

**Issue by brezinajn** [voythas/shine-unofficial#6]
Not sure if intended, but settings window does not use selected theme.

**Comment by voythas** [comment]
I honestly don't know why I did it that way. I remember considering doing that but somehow I had a reason not to.

Now I don't remember it, so I guess I will do it in future updates. :D

**Comment by brezinajn** [comment]
Sure :)

**Comment by dotvhs** [comment]
This is already done and it will be released in future version.
