### ISSUE TITLE
Customisable tile spacing

### ISSUE THREAD

**Issue by brezinajn** [voythas/shine-unofficial#7]
In grid view I feel there is bit too much space between tiles. I worked it around by setting page zoom to 90% and decreasing number of columns by one. My suggestion is to add margin settings. Google calendar uses something like that, where you can choose from 3 types of "density" comfortable, compact and cozy. I don't feel like this is necessary feature, because there is perfectly fine workaround, but since you wanted suggestions. Here you go :)

**Comment by dotvhs** [comment]
This will be added in next release.
