### ISSUE TITLE
Subscribe Button Issue

### ISSUE THREAD

**Issue by ghost** [voythas/shine-unofficial#8]
https://github.com/voythas/shine-unofficial/blob/6cb28be5525c69a1c31b383cae4b5c96b2ce5384/base.css#L2215

Please assign the appropriate element class to this. RES subscribe button in /r/all and /r/popular gets messed up because it's a 'button.
![2017-11-18_17-49-55](https://user-images.githubusercontent.com/33675519/32980279-5fbd9e28-cc89-11e7-8abf-e7609805000e.png)
'.

**Comment by dotvhs** [comment]
Will do, thanks for reporting.

**Comment by dotvhs** [comment]
This is already fixed in 1.7.0, which should be ready this month hopefully.
